### ISSUE TITLE
issue using mise with multiple self-hosted runners

### ISSUE THREAD

**Issue by ladislas** [jdx/mise-action#38]
We are starting to use mise to make sure the tools we use locally and in CI are the same. So far so good, mise is easy to use, config files are simple, everyone's happy.

For our CI, we are running our GitHub Actions on a self-hosted powerful machine with multiple runners running on the same machine.

We are having a lot of issues using mise in this setting, our actions fail with the following error:

```console
Error: The process '/Users/leka/.local/share/mise/bin/mise' failed with exit code null
```

<img width="1331" alt="Screenshot 2024-02-07 at 10 10 44" src="https://github.com/jdx/mise-action/assets/2206544/0cce55f5-917c-4c5a-a395-1df8522c89f9">

This happens when two actions are running at the same time and using the mise installed tools (in our case tuist, swiftfomat, swiftlint).

Is there a way to avoid this issue?

I'm thinking about setting the versions globally for our CI, and not using mise setup directly in our workflows, but I'm not sure it would work.

Thanks for your help :)

**Comment by ladislas** [comment]
Sometimes the error is a bit different

```console
Running mise --version
  /Users/leka/.local/share/mise/bin/mise --version
  Error: spawn Unknown system error -88
      at ChildProcess.spawn (node:internal/child_process:421:11)
      at Object.spawn (node:child_process:761:9)
      at ToolRunner.<anonymous> (/Users/leka/dev/ci/runner_iOS_2/_work/_actions/jdx/mise-action/v2/node_modules/@actions/exec/lib/toolrunner.js:413:1)
      at Generator.next (<anonymous>)
      at fulfilled (/Users/leka/dev/ci/runner_iOS_2/_work/_actions/jdx/mise-action/v2/node_modules/@actions/exec/lib/toolrunner.js:24:1)
```

**Comment by ladislas** [comment]
So I've managed to find a workaround:

- I've installed mise with brew on our CI machine
- In my workflows, I use `echo "$HOME/.local/share/mise/shims" >> $GITHUB_PATH` to access the tools
- I have a cron workflow that runs every night to `mise uninstall --all && mise install` the tools, pulling the new version if necessary
- The same workflow can also be triggered when the config file changes or with a label to a PR

**Comment by ladislas** [comment]
From my understanding, the problem with the action is the install/uninstall of mise itself with multiple workflows running on the same machine at the same time.

An option to use "system mise" could help fix the issue :)

**Comment by ladislas** [comment]
i'm closing the issue as we've moved to a different setup
